run:
  timeout: 3m

linters:
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - revive

issues:
  exclude-use-default: false

linters-settings:
  goimports:
    local-prefixes: github.com/lucrumx/bot