// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchange

import (
	"context"

	"github.com/lucrumx/bot/internal/exchange"
	"github.com/lucrumx/bot/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// CloseOrder provides a mock function for the type MockProvider
func (_mock *MockProvider) CloseOrder(ctx context.Context, order *models.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CloseOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_CloseOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseOrder'
type MockProvider_CloseOrder_Call struct {
	*mock.Call
}

// CloseOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *models.Order
func (_e *MockProvider_Expecter) CloseOrder(ctx interface{}, order interface{}) *MockProvider_CloseOrder_Call {
	return &MockProvider_CloseOrder_Call{Call: _e.mock.On("CloseOrder", ctx, order)}
}

func (_c *MockProvider_CloseOrder_Call) Run(run func(ctx context.Context, order *models.Order)) *MockProvider_CloseOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Order
		if args[1] != nil {
			arg1 = args[1].(*models.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_CloseOrder_Call) Return(err error) *MockProvider_CloseOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_CloseOrder_Call) RunAndReturn(run func(ctx context.Context, order *models.Order) error) *MockProvider_CloseOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockProvider
func (_mock *MockProvider) CreateOrder(ctx context.Context, order *models.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockProvider_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *models.Order
func (_e *MockProvider_Expecter) CreateOrder(ctx interface{}, order interface{}) *MockProvider_CreateOrder_Call {
	return &MockProvider_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *MockProvider_CreateOrder_Call) Run(run func(ctx context.Context, order *models.Order)) *MockProvider_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Order
		if args[1] != nil {
			arg1 = args[1].(*models.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_CreateOrder_Call) Return(err error) *MockProvider_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, order *models.Order) error) *MockProvider_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalances provides a mock function for the type MockProvider
func (_mock *MockProvider) GetBalances(ctx context.Context) ([]models.Balance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBalances")
	}

	var r0 []models.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Balance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Balance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalances'
type MockProvider_GetBalances_Call struct {
	*mock.Call
}

// GetBalances is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) GetBalances(ctx interface{}) *MockProvider_GetBalances_Call {
	return &MockProvider_GetBalances_Call{Call: _e.mock.On("GetBalances", ctx)}
}

func (_c *MockProvider_GetBalances_Call) Run(run func(ctx context.Context)) *MockProvider_GetBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_GetBalances_Call) Return(balances []models.Balance, err error) *MockProvider_GetBalances_Call {
	_c.Call.Return(balances, err)
	return _c
}

func (_c *MockProvider_GetBalances_Call) RunAndReturn(run func(ctx context.Context) ([]models.Balance, error)) *MockProvider_GetBalances_Call {
	_c.Call.Return(run)
	return _c
}

// GetExchangeName provides a mock function for the type MockProvider
func (_mock *MockProvider) GetExchangeName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExchangeName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_GetExchangeName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExchangeName'
type MockProvider_GetExchangeName_Call struct {
	*mock.Call
}

// GetExchangeName is a helper method to define mock.On call
func (_e *MockProvider_Expecter) GetExchangeName() *MockProvider_GetExchangeName_Call {
	return &MockProvider_GetExchangeName_Call{Call: _e.mock.On("GetExchangeName")}
}

func (_c *MockProvider_GetExchangeName_Call) Run(run func()) *MockProvider_GetExchangeName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_GetExchangeName_Call) Return(s string) *MockProvider_GetExchangeName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_GetExchangeName_Call) RunAndReturn(run func() string) *MockProvider_GetExchangeName_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstruments provides a mock function for the type MockProvider
func (_mock *MockProvider) GetInstruments(ctx context.Context) (map[string]exchange.Instrument, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInstruments")
	}

	var r0 map[string]exchange.Instrument
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]exchange.Instrument, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]exchange.Instrument); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]exchange.Instrument)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetInstruments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstruments'
type MockProvider_GetInstruments_Call struct {
	*mock.Call
}

// GetInstruments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) GetInstruments(ctx interface{}) *MockProvider_GetInstruments_Call {
	return &MockProvider_GetInstruments_Call{Call: _e.mock.On("GetInstruments", ctx)}
}

func (_c *MockProvider_GetInstruments_Call) Run(run func(ctx context.Context)) *MockProvider_GetInstruments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_GetInstruments_Call) Return(stringToInstrument map[string]exchange.Instrument, err error) *MockProvider_GetInstruments_Call {
	_c.Call.Return(stringToInstrument, err)
	return _c
}

func (_c *MockProvider_GetInstruments_Call) RunAndReturn(run func(ctx context.Context) (map[string]exchange.Instrument, error)) *MockProvider_GetInstruments_Call {
	_c.Call.Return(run)
	return _c
}

// GetTickers provides a mock function for the type MockProvider
func (_mock *MockProvider) GetTickers(ctx context.Context, symbols []string, category exchange.Category) ([]exchange.Ticker, error) {
	ret := _mock.Called(ctx, symbols, category)

	if len(ret) == 0 {
		panic("no return value specified for GetTickers")
	}

	var r0 []exchange.Ticker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, exchange.Category) ([]exchange.Ticker, error)); ok {
		return returnFunc(ctx, symbols, category)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, exchange.Category) []exchange.Ticker); ok {
		r0 = returnFunc(ctx, symbols, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]exchange.Ticker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, exchange.Category) error); ok {
		r1 = returnFunc(ctx, symbols, category)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetTickers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTickers'
type MockProvider_GetTickers_Call struct {
	*mock.Call
}

// GetTickers is a helper method to define mock.On call
//   - ctx context.Context
//   - symbols []string
//   - category exchange.Category
func (_e *MockProvider_Expecter) GetTickers(ctx interface{}, symbols interface{}, category interface{}) *MockProvider_GetTickers_Call {
	return &MockProvider_GetTickers_Call{Call: _e.mock.On("GetTickers", ctx, symbols, category)}
}

func (_c *MockProvider_GetTickers_Call) Run(run func(ctx context.Context, symbols []string, category exchange.Category)) *MockProvider_GetTickers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 exchange.Category
		if args[2] != nil {
			arg2 = args[2].(exchange.Category)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_GetTickers_Call) Return(tickers []exchange.Ticker, err error) *MockProvider_GetTickers_Call {
	_c.Call.Return(tickers, err)
	return _c
}

func (_c *MockProvider_GetTickers_Call) RunAndReturn(run func(ctx context.Context, symbols []string, category exchange.Category) ([]exchange.Ticker, error)) *MockProvider_GetTickers_Call {
	_c.Call.Return(run)
	return _c
}

// SetLeverage provides a mock function for the type MockProvider
func (_mock *MockProvider) SetLeverage(ctx context.Context, symbol string, leverage int64) error {
	ret := _mock.Called(ctx, symbol, leverage)

	if len(ret) == 0 {
		panic("no return value specified for SetLeverage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, symbol, leverage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_SetLeverage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLeverage'
type MockProvider_SetLeverage_Call struct {
	*mock.Call
}

// SetLeverage is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - leverage int64
func (_e *MockProvider_Expecter) SetLeverage(ctx interface{}, symbol interface{}, leverage interface{}) *MockProvider_SetLeverage_Call {
	return &MockProvider_SetLeverage_Call{Call: _e.mock.On("SetLeverage", ctx, symbol, leverage)}
}

func (_c *MockProvider_SetLeverage_Call) Run(run func(ctx context.Context, symbol string, leverage int64)) *MockProvider_SetLeverage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_SetLeverage_Call) Return(err error) *MockProvider_SetLeverage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_SetLeverage_Call) RunAndReturn(run func(ctx context.Context, symbol string, leverage int64) error) *MockProvider_SetLeverage_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeExecutions provides a mock function for the type MockProvider
func (_mock *MockProvider) SubscribeExecutions(ctx context.Context) (<-chan exchange.OrderExecutionEvent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeExecutions")
	}

	var r0 <-chan exchange.OrderExecutionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan exchange.OrderExecutionEvent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan exchange.OrderExecutionEvent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan exchange.OrderExecutionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_SubscribeExecutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeExecutions'
type MockProvider_SubscribeExecutions_Call struct {
	*mock.Call
}

// SubscribeExecutions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) SubscribeExecutions(ctx interface{}) *MockProvider_SubscribeExecutions_Call {
	return &MockProvider_SubscribeExecutions_Call{Call: _e.mock.On("SubscribeExecutions", ctx)}
}

func (_c *MockProvider_SubscribeExecutions_Call) Run(run func(ctx context.Context)) *MockProvider_SubscribeExecutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_SubscribeExecutions_Call) Return(orderExecutionEventCh <-chan exchange.OrderExecutionEvent, err error) *MockProvider_SubscribeExecutions_Call {
	_c.Call.Return(orderExecutionEventCh, err)
	return _c
}

func (_c *MockProvider_SubscribeExecutions_Call) RunAndReturn(run func(ctx context.Context) (<-chan exchange.OrderExecutionEvent, error)) *MockProvider_SubscribeExecutions_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeTrades provides a mock function for the type MockProvider
func (_mock *MockProvider) SubscribeTrades(ctx context.Context, symbols []string, category exchange.Category) (<-chan exchange.Trade, error) {
	ret := _mock.Called(ctx, symbols, category)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeTrades")
	}

	var r0 <-chan exchange.Trade
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, exchange.Category) (<-chan exchange.Trade, error)); ok {
		return returnFunc(ctx, symbols, category)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, exchange.Category) <-chan exchange.Trade); ok {
		r0 = returnFunc(ctx, symbols, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan exchange.Trade)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, exchange.Category) error); ok {
		r1 = returnFunc(ctx, symbols, category)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_SubscribeTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeTrades'
type MockProvider_SubscribeTrades_Call struct {
	*mock.Call
}

// SubscribeTrades is a helper method to define mock.On call
//   - ctx context.Context
//   - symbols []string
//   - category exchange.Category
func (_e *MockProvider_Expecter) SubscribeTrades(ctx interface{}, symbols interface{}, category interface{}) *MockProvider_SubscribeTrades_Call {
	return &MockProvider_SubscribeTrades_Call{Call: _e.mock.On("SubscribeTrades", ctx, symbols, category)}
}

func (_c *MockProvider_SubscribeTrades_Call) Run(run func(ctx context.Context, symbols []string, category exchange.Category)) *MockProvider_SubscribeTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 exchange.Category
		if args[2] != nil {
			arg2 = args[2].(exchange.Category)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_SubscribeTrades_Call) Return(tradeCh <-chan exchange.Trade, err error) *MockProvider_SubscribeTrades_Call {
	_c.Call.Return(tradeCh, err)
	return _c
}

func (_c *MockProvider_SubscribeTrades_Call) RunAndReturn(run func(ctx context.Context, symbols []string, category exchange.Category) (<-chan exchange.Trade, error)) *MockProvider_SubscribeTrades_Call {
	_c.Call.Return(run)
	return _c
}
