// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchange_arbitragebot

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/lucrumx/bot/internal/exchange/arbitragebot"
	"github.com/lucrumx/bot/internal/models"
)

// NewMockArbitrageSpreadRepository creates a new instance of MockArbitrageSpreadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArbitrageSpreadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArbitrageSpreadRepository {
	mock := &MockArbitrageSpreadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArbitrageSpreadRepository is an autogenerated mock type for the ArbitrageSpreadRepository type
type MockArbitrageSpreadRepository struct {
	mock.Mock
}

type MockArbitrageSpreadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArbitrageSpreadRepository) EXPECT() *MockArbitrageSpreadRepository_Expecter {
	return &MockArbitrageSpreadRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockArbitrageSpreadRepository
func (_mock *MockArbitrageSpreadRepository) Create(ctx context.Context, spread *models.ArbitrageSpread) error {
	ret := _mock.Called(ctx, spread)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ArbitrageSpread) error); ok {
		r0 = returnFunc(ctx, spread)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArbitrageSpreadRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockArbitrageSpreadRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spread *models.ArbitrageSpread
func (_e *MockArbitrageSpreadRepository_Expecter) Create(ctx interface{}, spread interface{}) *MockArbitrageSpreadRepository_Create_Call {
	return &MockArbitrageSpreadRepository_Create_Call{Call: _e.mock.On("Create", ctx, spread)}
}

func (_c *MockArbitrageSpreadRepository_Create_Call) Run(run func(ctx context.Context, spread *models.ArbitrageSpread)) *MockArbitrageSpreadRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.ArbitrageSpread
		if args[1] != nil {
			arg1 = args[1].(*models.ArbitrageSpread)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArbitrageSpreadRepository_Create_Call) Return(err error) *MockArbitrageSpreadRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArbitrageSpreadRepository_Create_Call) RunAndReturn(run func(ctx context.Context, spread *models.ArbitrageSpread) error) *MockArbitrageSpreadRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockArbitrageSpreadRepository
func (_mock *MockArbitrageSpreadRepository) FindAll(ctx context.Context, f arbitragebot.FindFilter) ([]*models.ArbitrageSpread, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*models.ArbitrageSpread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, arbitragebot.FindFilter) ([]*models.ArbitrageSpread, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, arbitragebot.FindFilter) []*models.ArbitrageSpread); ok {
		r0 = returnFunc(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ArbitrageSpread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, arbitragebot.FindFilter) error); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArbitrageSpreadRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockArbitrageSpreadRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - f arbitragebot.FindFilter
func (_e *MockArbitrageSpreadRepository_Expecter) FindAll(ctx interface{}, f interface{}) *MockArbitrageSpreadRepository_FindAll_Call {
	return &MockArbitrageSpreadRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, f)}
}

func (_c *MockArbitrageSpreadRepository_FindAll_Call) Run(run func(ctx context.Context, f arbitragebot.FindFilter)) *MockArbitrageSpreadRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 arbitragebot.FindFilter
		if args[1] != nil {
			arg1 = args[1].(arbitragebot.FindFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArbitrageSpreadRepository_FindAll_Call) Return(arbitrageSpreads []*models.ArbitrageSpread, err error) *MockArbitrageSpreadRepository_FindAll_Call {
	_c.Call.Return(arbitrageSpreads, err)
	return _c
}

func (_c *MockArbitrageSpreadRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, f arbitragebot.FindFilter) ([]*models.ArbitrageSpread, error)) *MockArbitrageSpreadRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneByOrderID provides a mock function for the type MockArbitrageSpreadRepository
func (_mock *MockArbitrageSpreadRepository) FindOneByOrderID(ctx context.Context, orderID uuid.UUID) (*models.ArbitrageSpread, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindOneByOrderID")
	}

	var r0 *models.ArbitrageSpread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.ArbitrageSpread, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.ArbitrageSpread); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ArbitrageSpread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArbitrageSpreadRepository_FindOneByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneByOrderID'
type MockArbitrageSpreadRepository_FindOneByOrderID_Call struct {
	*mock.Call
}

// FindOneByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockArbitrageSpreadRepository_Expecter) FindOneByOrderID(ctx interface{}, orderID interface{}) *MockArbitrageSpreadRepository_FindOneByOrderID_Call {
	return &MockArbitrageSpreadRepository_FindOneByOrderID_Call{Call: _e.mock.On("FindOneByOrderID", ctx, orderID)}
}

func (_c *MockArbitrageSpreadRepository_FindOneByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockArbitrageSpreadRepository_FindOneByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArbitrageSpreadRepository_FindOneByOrderID_Call) Return(arbitrageSpread *models.ArbitrageSpread, err error) *MockArbitrageSpreadRepository_FindOneByOrderID_Call {
	_c.Call.Return(arbitrageSpread, err)
	return _c
}

func (_c *MockArbitrageSpreadRepository_FindOneByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*models.ArbitrageSpread, error)) *MockArbitrageSpreadRepository_FindOneByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockArbitrageSpreadRepository
func (_mock *MockArbitrageSpreadRepository) Update(ctx context.Context, spread *models.ArbitrageSpread, where arbitragebot.FindFilter) error {
	ret := _mock.Called(ctx, spread, where)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ArbitrageSpread, arbitragebot.FindFilter) error); ok {
		r0 = returnFunc(ctx, spread, where)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArbitrageSpreadRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockArbitrageSpreadRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - spread *models.ArbitrageSpread
//   - where arbitragebot.FindFilter
func (_e *MockArbitrageSpreadRepository_Expecter) Update(ctx interface{}, spread interface{}, where interface{}) *MockArbitrageSpreadRepository_Update_Call {
	return &MockArbitrageSpreadRepository_Update_Call{Call: _e.mock.On("Update", ctx, spread, where)}
}

func (_c *MockArbitrageSpreadRepository_Update_Call) Run(run func(ctx context.Context, spread *models.ArbitrageSpread, where arbitragebot.FindFilter)) *MockArbitrageSpreadRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.ArbitrageSpread
		if args[1] != nil {
			arg1 = args[1].(*models.ArbitrageSpread)
		}
		var arg2 arbitragebot.FindFilter
		if args[2] != nil {
			arg2 = args[2].(arbitragebot.FindFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockArbitrageSpreadRepository_Update_Call) Return(err error) *MockArbitrageSpreadRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArbitrageSpreadRepository_Update_Call) RunAndReturn(run func(ctx context.Context, spread *models.ArbitrageSpread, where arbitragebot.FindFilter) error) *MockArbitrageSpreadRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
