// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchange_arbitragebot

import (
	mock "github.com/stretchr/testify/mock"

	"github.com/lucrumx/bot/internal/models"
)

// NewMockBalanceStore creates a new instance of MockBalanceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceStore {
	mock := &MockBalanceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceStore is an autogenerated mock type for the BalanceStore type
type MockBalanceStore struct {
	mock.Mock
}

type MockBalanceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceStore) EXPECT() *MockBalanceStore_Expecter {
	return &MockBalanceStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockBalanceStore
func (_mock *MockBalanceStore) Get(exchange string) ([]models.Balance, bool) {
	ret := _mock.Called(exchange)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []models.Balance
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.Balance, bool)); ok {
		return returnFunc(exchange)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.Balance); ok {
		r0 = returnFunc(exchange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(exchange)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockBalanceStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBalanceStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - exchange string
func (_e *MockBalanceStore_Expecter) Get(exchange interface{}) *MockBalanceStore_Get_Call {
	return &MockBalanceStore_Get_Call{Call: _e.mock.On("Get", exchange)}
}

func (_c *MockBalanceStore_Get_Call) Run(run func(exchange string)) *MockBalanceStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBalanceStore_Get_Call) Return(balances []models.Balance, b bool) *MockBalanceStore_Get_Call {
	_c.Call.Return(balances, b)
	return _c
}

func (_c *MockBalanceStore_Get_Call) RunAndReturn(run func(exchange string) ([]models.Balance, bool)) *MockBalanceStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetForAsset provides a mock function for the type MockBalanceStore
func (_mock *MockBalanceStore) GetForAsset(exchange string, asset string) (models.Balance, bool) {
	ret := _mock.Called(exchange, asset)

	if len(ret) == 0 {
		panic("no return value specified for GetForAsset")
	}

	var r0 models.Balance
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (models.Balance, bool)); ok {
		return returnFunc(exchange, asset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) models.Balance); ok {
		r0 = returnFunc(exchange, asset)
	} else {
		r0 = ret.Get(0).(models.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(exchange, asset)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockBalanceStore_GetForAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForAsset'
type MockBalanceStore_GetForAsset_Call struct {
	*mock.Call
}

// GetForAsset is a helper method to define mock.On call
//   - exchange string
//   - asset string
func (_e *MockBalanceStore_Expecter) GetForAsset(exchange interface{}, asset interface{}) *MockBalanceStore_GetForAsset_Call {
	return &MockBalanceStore_GetForAsset_Call{Call: _e.mock.On("GetForAsset", exchange, asset)}
}

func (_c *MockBalanceStore_GetForAsset_Call) Run(run func(exchange string, asset string)) *MockBalanceStore_GetForAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceStore_GetForAsset_Call) Return(balance models.Balance, b bool) *MockBalanceStore_GetForAsset_Call {
	_c.Call.Return(balance, b)
	return _c
}

func (_c *MockBalanceStore_GetForAsset_Call) RunAndReturn(run func(exchange string, asset string) (models.Balance, bool)) *MockBalanceStore_GetForAsset_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockBalanceStore
func (_mock *MockBalanceStore) Set(exchange string, balances []models.Balance) {
	_mock.Called(exchange, balances)
	return
}

// MockBalanceStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockBalanceStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - exchange string
//   - balances []models.Balance
func (_e *MockBalanceStore_Expecter) Set(exchange interface{}, balances interface{}) *MockBalanceStore_Set_Call {
	return &MockBalanceStore_Set_Call{Call: _e.mock.On("Set", exchange, balances)}
}

func (_c *MockBalanceStore_Set_Call) Run(run func(exchange string, balances []models.Balance)) *MockBalanceStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []models.Balance
		if args[1] != nil {
			arg1 = args[1].([]models.Balance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceStore_Set_Call) Return() *MockBalanceStore_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBalanceStore_Set_Call) RunAndReturn(run func(exchange string, balances []models.Balance)) *MockBalanceStore_Set_Call {
	_c.Run(run)
	return _c
}
