// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchange_arbitragebot

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	"github.com/lucrumx/bot/internal/models"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Create(ctx context.Context, order *models.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *models.Order
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, order interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, order *models.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Order
		if args[1] != nil {
			arg1 = args[1].(*models.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(err error) *MockOrderRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, order *models.Order) error) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFilled provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) UpdateFilled(ctx context.Context, id uuid.UUID, avgPrice decimal.Decimal, executedQty decimal.Decimal) error {
	ret := _mock.Called(ctx, id, avgPrice, executedQty)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFilled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, id, avgPrice, executedQty)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_UpdateFilled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFilled'
type MockOrderRepository_UpdateFilled_Call struct {
	*mock.Call
}

// UpdateFilled is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - avgPrice decimal.Decimal
//   - executedQty decimal.Decimal
func (_e *MockOrderRepository_Expecter) UpdateFilled(ctx interface{}, id interface{}, avgPrice interface{}, executedQty interface{}) *MockOrderRepository_UpdateFilled_Call {
	return &MockOrderRepository_UpdateFilled_Call{Call: _e.mock.On("UpdateFilled", ctx, id, avgPrice, executedQty)}
}

func (_c *MockOrderRepository_UpdateFilled_Call) Run(run func(ctx context.Context, id uuid.UUID, avgPrice decimal.Decimal, executedQty decimal.Decimal)) *MockOrderRepository_UpdateFilled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 decimal.Decimal
		if args[2] != nil {
			arg2 = args[2].(decimal.Decimal)
		}
		var arg3 decimal.Decimal
		if args[3] != nil {
			arg3 = args[3].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepository_UpdateFilled_Call) Return(err error) *MockOrderRepository_UpdateFilled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_UpdateFilled_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, avgPrice decimal.Decimal, executedQty decimal.Decimal) error) *MockOrderRepository_UpdateFilled_Call {
	_c.Call.Return(run)
	return _c
}
